sudo: required
services: docker
before_install:
  - sudo pip install csup
  - export RPRE=stevemcgrath
  - export RNAME=nessus_monitor
script:
  - docker build --no-cache . -t nnm:latest
#  - |
#    csup upload nessus_scanner --tag latest \
#      --consec-name sensors/nessus --consec-tag latest -rp
after_success: ./deploy.sh